# Generated by Django 3.0.1 on 2020-03-22 15:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 3, 22, 15, 58, 52, 854923, tzinfo=utc))),
                ('max_stages', models.PositiveSmallIntegerField(default=1)),
                ('current_stage', models.PositiveSmallIntegerField(default=1)),
                ('finished', models.BooleanField(default=False)),
                ('category', models.CharField(default='other', max_length=200)),
                ('bracket_type', models.CharField(choices=[('SE', 'Single elimination')], default='SE', max_length=2)),
                ('hosts', models.ManyToManyField(related_name='hosted_tournaments', to='core.Player')),
                ('players', models.ManyToManyField(blank=True, related_name='played_tournaments', to='core.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Stats'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 3, 22, 15, 58, 52, 856332, tzinfo=utc))),
                ('finished', models.BooleanField(default=False)),
                ('p1_score', models.PositiveSmallIntegerField(default=0)),
                ('p2_score', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.PositiveSmallIntegerField(default=1)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p1', to='core.Player')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p2', to='core.Player')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tournament')),
            ],
        ),
    ]
