# Generated by Django 3.0.1 on 2020-03-22 17:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200322_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Stats'),
        ),
        migrations.AddField(
            model_name='stats',
            name='loses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 17, 18, 19, 552327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 17, 18, 19, 550765, tzinfo=utc)),
        ),
    ]
