# Generated by Django 3.0.1 on 2020-03-22 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200322_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 20, 24, 39, 144611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 20, 24, 39, 143235, tzinfo=utc)),
        ),
    ]
