# Generated by Django 3.0.1 on 2020-03-24 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200324_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players_can_join',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 18, 45, 38, 834456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 18, 45, 38, 832443, tzinfo=utc)),
        ),
    ]
