# Generated by Django 2.2.7 on 2019-12-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191223_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='host',
            new_name='hosts',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='player',
            new_name='players',
        ),
    ]
