# Generated by Django 3.0.1 on 2019-12-23 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191223_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 16, 47, 55, 282696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 16, 47, 55, 281248, tzinfo=utc)),
        ),
    ]
