# Generated by Django 3.0.1 on 2019-12-23 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191223_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 17, 32, 15, 309119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 17, 32, 15, 307607, tzinfo=utc)),
        ),
    ]
