# Generated by Django 3.0.1 on 2019-12-30 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191223_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 17, 26, 48, 518767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 17, 26, 48, 517208, tzinfo=utc)),
        ),
    ]
